version: '2.4'

services:
  server:
    build: ./server
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    env_file: ./server/.env
    environment:
      - NODE_ENV=development

  client:
    build: ./client
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "3000:3000"
    stdin_open: true

  mongo:
    image: mongo
    volumes:
      - dev-db:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet

volumes:
    dev-db:
