version: '2'

services:
  server:
    build: .
    image: mern-docker-test
    container_name: mern-docker-test-server
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file: .env
    environment: 
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB

  db:
    image: mongo
    container_name: mern-docker-test-db
    # ports:
      # - "27017:27017"
